# .rubocop.yml
inherit_from:
  - https://raw.githubusercontent.com/Geezeo/rubocop/develop/.rubocop-rspec_rails.yml
  - https://raw.githubusercontent.com/Geezeo/rubocop/develop/.rubocop-rspec.yml
  - https://raw.githubusercontent.com/Geezeo/rubocop/develop/.rubocop-rake.yml
  - https://raw.githubusercontent.com/Geezeo/rubocop/develop/.rubocop-rails.yml
  - https://raw.githubusercontent.com/Geezeo/rubocop/develop/.rubocop-performance.yml

require:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.2
  TargetRailsVersion: 7.0
  NewCops: enable
  Exclude:
    - '**/db/migrate/*'
    - 'db/schema.rb'
    - '**/Gemfile.lock'
    - '**/Rakefile'
    - '**/rails'
    - '**/vendor/**/*'
    - '**/spec_helper.rb'
    - 'node_modules/**/*'
    - 'bin/*'

Style/Documentation:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false